#pragma once

UENUM()
enum EWidgetEnum
{
	WIDGET_NONE,
	WIDGET_MAIN_MENU,
	WIDGET_NEW_GAME,
	WIDGET_LOAD_GAME,
	WIDGET_RUSH_MODE,
	WIDGET_OPTIONS,
	WIDGET_EXTRA,
	WIDGET_DIFFICULTY,
	WIDGET_CONFIRM,
	WIDGET_PLAYER,
	WIDGET_BOSS,
	WIDGET_PAUSE,
	WIDGET_LOADING,
	WIDGET_ELEVATOR,
	WIDGET_CHEST_SPAM,
	WIDGET_CHEST_QTE,
	WIDGET_TUTO,
	WIDGET_WARNINGS_ZONE,
	WIDGET_POPUP,
	WIDGET_BOSS_RUSH,
	WIDGET_CINEMATIC,
	WIDGET_CALIBRATION,
	WIDGET_CREDIT	
};
